Use github version of blackfriday/v2 and remove dep files
The blackfriday gopkg.in release is broken when using `go mod vendor`
and building a project dependent on bfchroma with `go build -mod=vendor`
and `go version go1.12.2 gccgo (GCC) 9.2.0 linux/amd64`.

The build fails with:

goroutine 1 [running]:
runtime..z2fdebug.Stack
	/build/gcc/src/gcc/libgo/go/runtime/debug/stack.go:24
runtime..z2fdebug.PrintStack
	/build/gcc/src/gcc/libgo/go/runtime/debug/stack.go:16
main.main
	:0
build derpderp: cannot find module for path github.com/shurcooL/sanitized_anchor_name

Fix this by pointing to the github.com release of blackfriday instead in
bfchroma's go.mod. Take this opportunity to also remove remaining dep
files. Another benefit is that the `replace` directive in go.mod to
workaround some blackfriday release confusion is no longer required
(neither in bfchroma nor in any packages using bfchroma).

Signed-off-by: Christopher M. Riedl <cmr@informatik.wtf>